<?php

namespace AppBundle\Repository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use AppBundle\Entity\Ship;
use AppBundle\Entity\Travel;
use AppBundle\Entity\Harbor;

/**
 * ShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipRepository extends ServiceEntityRepository//\Doctrine\ORM\EntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Ship::class, Travel::class, Harbor::class);
    }

    // This will return a QueryBuilder instance
    public function qbAll()
    {
        return $this->createQueryBuilder("s");
    }

    public function restrictedInformationShips(?array $collumns = ['id'], ?int $limit = 10, ?int $offset = 0, ?bool $count = false): array
    {
        $table    = $this->getClassMetadata()->table["name"];

        if ($count) {
            $select = 'COUNT(id) as count';
            $limit  = '';
        }
        else {
            $collumns = (!is_array($collumns) || empty($collumns) ? ['id'] : $collumns);
            $select   = implode(', ', $collumns);
            $limit    = ' LIMIT '. $offset .', '. $limit;
        }

        $sql =  'SELECT '. $select .' FROM '. $table . $limit;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        return $stmt->fetchAll();
    }

    public function restrictedInformationShip(int $id, ?array $collumns = ['id']): ?array
    {
        $collumns = (!is_array($collumns) || empty($collumns) ? ['id'] : $collumns);
        $table    = $this->getClassMetadata()->table["name"];

        $sql =  'SELECT '. implode(', ', $collumns) .' FROM '. $table .' WHERE id = :id';

        $stmt   = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute([':id' => $id]);
        $result = $stmt->fetch();
        $result = is_array($result) ? $result : null;

        return $result;
    }

    public function restrictedInformationHarborShips(int $harborId, ?array $collumns = ['id'], ?int $limit = 10, ?int $offset = 0, ?bool $count = false): array
    {
        $travelMetas         = $this->getEntityManager()->getClassMetadata(Travel::class);
        $travelTableName     = $travelMetas->table["name"];
        $table               = $this->getClassMetadata()->table["name"];

        if ($count) {
            $select = 'COUNT(s.id) as count';
            $limit  = '';
        }
        else {
            $collumns = (!is_array($collumns) || empty($collumns) ? ['id'] : $collumns);
            array_walk($collumns, function(&$value) {
                $value = 's.'.$value;
            });
            $select   = implode(', ', $collumns);
            $limit    = ' LIMIT '. $offset .', '. $limit;
        }

        $sql = 'SELECT '. $select .'
        FROM (SELECT arival_id, ship_id 
              FROM '. $travelTableName .' GROUP BY ship_id 
              ORDER BY travel_date DESC) arivals
        JOIN '. $table .' s ON (arivals.ship_id = s.id)
        WHERE arivals.arival_id = :harbor_id'
        .$limit;

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute([':harbor_id' => $harborId]);

        return $stmt->fetchAll();
    }

    public function shipCanAccessHarbor(int $shipId, int $harborId, ?array $collumns = ['id']): array
    {
        $shipMetas           = $this->getEntityManager()->getClassMetadata(Ship::class);
        $shipTableName       = $shipMetas->table["name"];
        $harborMetas         = $this->getEntityManager()->getClassMetadata(Harbor::class);
        $harborJobsTableName = $harborMetas->associationMappings['jobs']['joinTable']['name'];
        $table               = $this->getEntityManager()->getClassMetadata(Harbor::class)->table["name"];

        $collumns = (!is_array($collumns) || empty($collumns) ? ['id'] : $collumns);
        array_walk($collumns, function(&$value) {
            $value = 'h.'.$value;
        });
        $select   = implode(', ', $collumns);

        $sql = 'SELECT '. $select .'
                FROM '. $table .' h 
                JOIN '. $harborJobsTableName .' hj ON (h.id = hj.harbor_id AND h.id = :harbor_id) 
                JOIN '. $shipTableName .' s ON (s.id = :ship_id AND hj.job_id = s.job_id AND s.drought <= h.drought_allowed AND s.length <= h.max_allowed_length AND s.width <= h.max_allowed_width)
                GROUP BY h.id';

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute([':ship_id' => $shipId, ':harbor_id' => $harborId]);
        $harbor = $stmt->fetch();

        if (!$harbor) {
            return array();
        }

        return $harbor;
    }
}
